### ISSUE TITLE
indirect type SN tansmit problem

### ISSUE THREAD

**Issue by newZland** [Eawag-SWW/loramesh#2]
hello,I search a paper which you publish in ieee access,and then download this code.But i found there doesn't have indirect type SN join process code  in function proc_join (proc_join.c:93) .what I wanna know is this software version just supporting direction sn?I'll be glad to see your reply,thank you.

**Comment by ebichris** [comment]
Hi newZland, that is correct, unfortunately the indirect join is not yet implemented in this version

**Comment by newZland** [comment]
anyway,thank you for your reply,hope for your new update version on this project.
